# Font (use a Nerd Font with ligatures for LazyVim icons & LSP symbols)
font_family      FiraCode Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size          10
enable_ligatures   yes

# Performance / latency
input_delay        0
repaint_delay      2
sync_to_monitor    no

# Tabs
tab_bar_style      powerline
tab_powerline_style slanted
tab_bar_edge       bottom
tab_bar_min_tabs   1

# Remote control (for neovim/kitty integration)
allow_remote_control yes
listen_on unix:/tmp/kitty
