theme = "snazzy"

[editor]
mouse = false
line-number = "relative"
cursorline = true
bufferline = "multiple"
color-modes = true
true-color = true
auto-format = true
smart-tab = { enable = true }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = false
display-messages = true

[keys.normal]
y = [":clipboard-yank", "yank"]
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
C-s = ":w"
C-q = ":q"

[keys.select]
y = [":clipboard-yank", "yank"]
p = [":clipboard-paste-after"]
P = [":clipboard-paste-before"]

[keys.insert]
C-s = ["normal_mode", ":w", "insert_mode"]
C-q = ["normal_mode", ":q"]
