[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[[language]]
name = "python"
language-servers = [{ name = "ruff" }]
auto-format = true
formatter = { command = "ruff", args = ["format", "--stdin-filename", "%{buffer_name}"] }
rulers = [88]
text-width = 88
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true
formatter = { command = "rustfmt", args = ["--emit", "stdout"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path=%{buffer_name}"] }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path=%{buffer_name}"] }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path=%{buffer_name}"] }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path=%{buffer_name}"] }
indent = { tab-width = 2, unit = "  " }
